# Generated by Django 4.2.6 on 2023-11-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_options_rename_timestamp_post_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-publish_date', '-created']},
        ),
    ]
