# Generated by Django 4.2.7 on 2023-12-08 03:27

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=slugger.fields.AutoSlugField(max_length=255, populate_from='title', unique=True),
        ),
    ]
