# Generated by Django 4.2.6 on 2023-11-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_options_remove_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date', '-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='created',
        ),
    ]
