# Generated by Django 4.2.7 on 2023-12-24 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_options_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-publish_date', '-created']},
        ),
    ]
