# Generated by Django 4.2.7 on 2023-12-06 01:31

from django.db import migrations
import markdownfield.models

def save_content_rendered(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownfield.models.MarkdownField(rendered_field='content_rendered'),
        ),
        migrations.RunPython(save_content_rendered),
    ]
