# Generated by Django 4.2.7 on 2024-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_is_public_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_public_parent',
            field=models.BooleanField(),
        ),
    ]
